<?php
/**
 * @file
 * humanitarianresponse_layout.features.fe_block_settings.inc
 */

/**
 * Implements hook_default_fe_block_settings().
 */
function humanitarianresponse_layout_default_fe_block_settings() {
  $export = array();

  // bartik
  $theme = array();

  $theme['block-contact'] = array(
    'module' => 'block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'contact',
  );

  $theme['block-legal'] = array(
    'module' => 'block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'legal',
  );

  $theme['block-home_calendar_text'] = array(
    'module' => 'block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_calendar_text',
  );

  $theme['block-home_cod_text'] = array(
    'module' => 'block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_cod_text',
  );

  $theme['facetapi-FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao'] = array(
    'module' => 'facetapi',
    'delta' => 'FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-JAKZs3absS9kL1zrH6idqbCFj61Z4SpL'] = array(
    'module' => 'facetapi',
    'delta' => 'JAKZs3absS9kL1zrH6idqbCFj61Z4SpL',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Nars6CXEF2stEbUlZR8NEnqEtBDARTb1'] = array(
    'module' => 'facetapi',
    'delta' => 'Nars6CXEF2stEbUlZR8NEnqEtBDARTb1',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp'] = array(
    'module' => 'facetapi',
    'delta' => 'SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW'] = array(
    'module' => 'facetapi',
    'delta' => 'Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E'] = array(
    'module' => 'facetapi',
    'delta' => 'UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Uz43FkEp5BeMap09k2L4q5cxiMpioh2N'] = array(
    'module' => 'facetapi',
    'delta' => 'Uz43FkEp5BeMap09k2L4q5cxiMpioh2N',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-WaEgyIn8f6HkMj1R536Y3vBptvKRj30W'] = array(
    'module' => 'facetapi',
    'delta' => 'WaEgyIn8f6HkMj1R536Y3vBptvKRj30W',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl'] = array(
    'module' => 'facetapi',
    'delta' => 'YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm'] = array(
    'module' => 'facetapi',
    'delta' => 'cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-rOO3lO2B480jNa51cz03IJgosO6bbCBm'] = array(
    'module' => 'facetapi',
    'delta' => 'rOO3lO2B480jNa51cz03IJgosO6bbCBm',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz'] = array(
    'module' => 'facetapi',
    'delta' => 'stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['follow-site'] = array(
    'module' => 'follow',
    'delta' => 'site',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => 1,
  );

  $theme['lang_dropdown-language'] = array(
    'module' => 'lang_dropdown',
    'delta' => 'language',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['logintoboggan-logintoboggan_logged_in'] = array(
    'module' => 'logintoboggan',
    'delta' => 'logintoboggan_logged_in',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['search_api_page-search_page'] = array(
    'module' => 'search_api_page',
    'delta' => 'search_page',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
  );

  $theme['system-main'] = array(
    'module' => 'system',
    'delta' => 'main',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['system-main-menu'] = array(
    'module' => 'system',
    'delta' => 'main-menu',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['user-login'] = array(
    'module' => 'user',
    'delta' => 'login',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-clusters-block'] = array(
    'module' => 'views',
    'delta' => 'clusters-block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-coordination_hubs-block'] = array(
    'module' => 'views',
    'delta' => 'coordination_hubs-block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-funding-block'] = array(
    'module' => 'views',
    'delta' => 'funding-block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-links-block'] = array(
    'module' => 'views',
    'delta' => 'links-block',
    'theme' => 'bartik',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $export['bartik'] = $theme;

  // humanitarianresponse
  $theme = array();

  $theme['block-contact'] = array(
    'module' => 'block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '0',
    'region' => 'postscript_first',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => 'Contact',
    'cache' => -1,
    'machine_name' => 'contact',
  );

  $theme['block-legal'] = array(
    'module' => 'block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '0',
    'region' => 'postscript_fourth',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => 'Legal',
    'cache' => -1,
    'machine_name' => 'legal',
  );

  $theme['block-home_calendar_text'] = array(
    'module' => 'block',
    'theme' => 'humanitarianresponse',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_calendar_text',
  );

  $theme['block-home_cod_text'] = array(
    'module' => 'block',
    'theme' => 'humanitarianresponse',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_cod_text',
  );

  $theme['facetapi-FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao'] = array(
    'module' => 'facetapi',
    'delta' => 'FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-15',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-JAKZs3absS9kL1zrH6idqbCFj61Z4SpL'] = array(
    'module' => 'facetapi',
    'delta' => 'JAKZs3absS9kL1zrH6idqbCFj61Z4SpL',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-17',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Nars6CXEF2stEbUlZR8NEnqEtBDARTb1'] = array(
    'module' => 'facetapi',
    'delta' => 'Nars6CXEF2stEbUlZR8NEnqEtBDARTb1',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-13',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp'] = array(
    'module' => 'facetapi',
    'delta' => 'SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-19',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW'] = array(
    'module' => 'facetapi',
    'delta' => 'Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-22',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E'] = array(
    'module' => 'facetapi',
    'delta' => 'UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-18',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Uz43FkEp5BeMap09k2L4q5cxiMpioh2N'] = array(
    'module' => 'facetapi',
    'delta' => 'Uz43FkEp5BeMap09k2L4q5cxiMpioh2N',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-11',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-WaEgyIn8f6HkMj1R536Y3vBptvKRj30W'] = array(
    'module' => 'facetapi',
    'delta' => 'WaEgyIn8f6HkMj1R536Y3vBptvKRj30W',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-16',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl'] = array(
    'module' => 'facetapi',
    'delta' => 'YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-20',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm'] = array(
    'module' => 'facetapi',
    'delta' => 'cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-21',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-rOO3lO2B480jNa51cz03IJgosO6bbCBm'] = array(
    'module' => 'facetapi',
    'delta' => 'rOO3lO2B480jNa51cz03IJgosO6bbCBm',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-14',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz'] = array(
    'module' => 'facetapi',
    'delta' => 'stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-12',
    'region' => 'sidebar_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['follow-site'] = array(
    'module' => 'follow',
    'delta' => 'site',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '0',
    'region' => 'postscript_third',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => 1,
  );

  $theme['lang_dropdown-language'] = array(
    'module' => 'lang_dropdown',
    'delta' => 'language',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-22',
    'region' => 'user_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '<none>',
    'cache' => -1,
  );

  $theme['logintoboggan-logintoboggan_logged_in'] = array(
    'module' => 'logintoboggan',
    'delta' => 'logintoboggan_logged_in',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-21',
    'region' => 'user_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '<none>',
    'cache' => -1,
  );

  $theme['search_api_page-search_page'] = array(
    'module' => 'search_api_page',
    'delta' => 'search_page',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-20',
    'region' => 'user_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '<none>',
    'cache' => '1',
  );

  $theme['system-main'] = array(
    'module' => 'system',
    'delta' => 'main',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-7',
    'region' => 'content',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['system-main-menu'] = array(
    'module' => 'system',
    'delta' => 'main-menu',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-23',
    'region' => 'menu',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '<none>',
    'cache' => -1,
  );

  $theme['user-login'] = array(
    'module' => 'user',
    'delta' => 'login',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-23',
    'region' => 'user_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '<none>',
    'cache' => -1,
  );

  $theme['views-clusters-block'] = array(
    'module' => 'views',
    'delta' => 'clusters-block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-22',
    'region' => 'sidebar_first',
    'custom' => '0',
    'visibility' => '1',
    'pages' => 'clusters/*',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-coordination_hubs-block'] = array(
    'module' => 'views',
    'delta' => 'coordination_hubs-block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-21',
    'region' => 'sidebar_first',
    'custom' => '0',
    'visibility' => '1',
    'pages' => 'coordination-hubs/*',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-funding-block'] = array(
    'module' => 'views',
    'delta' => 'funding-block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-20',
    'region' => 'sidebar_first',
    'custom' => '0',
    'visibility' => '1',
    'pages' => 'funding/*',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-links-block'] = array(
    'module' => 'views',
    'delta' => 'links-block',
    'theme' => 'humanitarianresponse',
    'status' => '1',
    'weight' => '-5',
    'region' => 'postscript_second',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $export['humanitarianresponse'] = $theme;

  // seven
  $theme = array();

  $theme['block-contact'] = array(
    'module' => 'block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'contact',
  );

  $theme['block-legal'] = array(
    'module' => 'block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'legal',
  );

  $theme['block-home_calendar_text'] = array(
    'module' => 'block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_calendar_text',
  );

  $theme['block-home_cod_text'] = array(
    'module' => 'block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
    'machine_name' => 'home_cod_text',
  );

  $theme['facetapi-FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao'] = array(
    'module' => 'facetapi',
    'delta' => 'FKBVzvYt9xMqDr8L58X0KOiiv1D8E5Ao',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-JAKZs3absS9kL1zrH6idqbCFj61Z4SpL'] = array(
    'module' => 'facetapi',
    'delta' => 'JAKZs3absS9kL1zrH6idqbCFj61Z4SpL',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Nars6CXEF2stEbUlZR8NEnqEtBDARTb1'] = array(
    'module' => 'facetapi',
    'delta' => 'Nars6CXEF2stEbUlZR8NEnqEtBDARTb1',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp'] = array(
    'module' => 'facetapi',
    'delta' => 'SRTVUTAsjHh8QrIHE2NMBl3MM1s3qOKp',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW'] = array(
    'module' => 'facetapi',
    'delta' => 'Shb0Q1vWgCArrHrjHszTyhl2jaEhIjzW',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E'] = array(
    'module' => 'facetapi',
    'delta' => 'UrbbwTPM31dQGgHrSt9Tjdnblkw12f6E',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-Uz43FkEp5BeMap09k2L4q5cxiMpioh2N'] = array(
    'module' => 'facetapi',
    'delta' => 'Uz43FkEp5BeMap09k2L4q5cxiMpioh2N',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-WaEgyIn8f6HkMj1R536Y3vBptvKRj30W'] = array(
    'module' => 'facetapi',
    'delta' => 'WaEgyIn8f6HkMj1R536Y3vBptvKRj30W',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl'] = array(
    'module' => 'facetapi',
    'delta' => 'YQrWdaYB0Jm9BGw7VcgHFswJHlxawCsl',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm'] = array(
    'module' => 'facetapi',
    'delta' => 'cpoyWFNPOVLHvKGY6t6bb8LVM41Xs2Dm',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-rOO3lO2B480jNa51cz03IJgosO6bbCBm'] = array(
    'module' => 'facetapi',
    'delta' => 'rOO3lO2B480jNa51cz03IJgosO6bbCBm',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['facetapi-stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz'] = array(
    'module' => 'facetapi',
    'delta' => 'stEMVIWfiMnc0Su1rCOk69GTqqvFjXLz',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['follow-site'] = array(
    'module' => 'follow',
    'delta' => 'site',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => 1,
  );

  $theme['lang_dropdown-language'] = array(
    'module' => 'lang_dropdown',
    'delta' => 'language',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['logintoboggan-logintoboggan_logged_in'] = array(
    'module' => 'logintoboggan',
    'delta' => 'logintoboggan_logged_in',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['search_api_page-search_page'] = array(
    'module' => 'search_api_page',
    'delta' => 'search_page',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => '1',
  );

  $theme['system-main'] = array(
    'module' => 'system',
    'delta' => 'main',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['system-main-menu'] = array(
    'module' => 'system',
    'delta' => 'main-menu',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['user-login'] = array(
    'module' => 'user',
    'delta' => 'login',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-clusters-block'] = array(
    'module' => 'views',
    'delta' => 'clusters-block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-coordination_hubs-block'] = array(
    'module' => 'views',
    'delta' => 'coordination_hubs-block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-funding-block'] = array(
    'module' => 'views',
    'delta' => 'funding-block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $theme['views-links-block'] = array(
    'module' => 'views',
    'delta' => 'links-block',
    'theme' => 'seven',
    'status' => 0,
    'weight' => '0',
    'region' => '',
    'custom' => '0',
    'visibility' => '0',
    'pages' => '',
    'title' => '',
    'cache' => -1,
  );

  $export['seven'] = $theme;

  $theme_default = variable_get('theme_default', 'garland');
  $themes = list_themes();
  foreach ($export as $theme_key => $settings) {
    if ($theme_key != $theme_default && empty($themes[$theme_key]->status)) {
      unset($export[$theme_key]);
    }
  }
  return $export;
}
